### ISSUE TITLE
When using more paths, POST parameters are lost in second route

### ISSUE THREAD

**Issue by dbshell** [moleculerjs/moleculer-web#101] opened 2019-01-17 19:31 UTC
I have following sample code:

```javascript
const { ServiceBroker } = require("moleculer");
const ApiService = require("moleculer-web");

// Create a broker
let broker = new ServiceBroker({ logger: console });

// Create a service
broker.createService({
  name: "test1",
  actions: {
    hello(ctx) {
      console.log(ctx.params);
      return "test1:" + JSON.stringify(ctx.params.entities);
    }
  }
});
// Create a service
broker.createService({
  name: "test2",
  actions: {
    hello(ctx) {
      console.log(ctx.params);
      return "test2:" + JSON.stringify(ctx.params.entities);
    }
  }
});

// Load API Gateway
broker.createService({
  name: "api",
  mixins: [ApiService],
  settings: {
    routes: [
      {
        path: "/api1",
        whitelist: ["test1.hello"]
      },
      {
        path: "/api2",
        whitelist: ["test2.hello"]
      }
    ]
  }
});

// Start server
broker.start();
```

When I call POST http://localhost:3000/api1/test1/hello with POST body 
```javascript
{
	"entities": [1,2,3]
}
```
it returns correctly "test1:[1,2,3]", but when I call the same POST, but on URL  http://localhost:3000/api2/test2/hello (on route, which is registrated the second), it returns ""test2:undefined" - POST parameter is lost. GET parameters works correctly in all registered routes.

**Comment by icebob** [comment] 2019-01-18 18:08
It's weird, but I could reproduce with your code. I'm debugging...

**Comment by icebob** [comment] 2019-01-18 18:15
The problem is that you should enable body-parsers explicitly:

```js
const { ServiceBroker } = require("moleculer");
const ApiService = require("moleculer-web");

// Create a broker
let broker = new ServiceBroker({ logger: console });

// Create a service
broker.createService({
    name: "test1",
    actions: {
        hello(ctx) {
            console.log(ctx.params);
            return "test1:" + JSON.stringify(ctx.params.entities);
        }
    }
});
// Create a service
broker.createService({
    name: "test2",
    actions: {
        hello(ctx) {
            console.log(ctx.params);
            return "test2:" + JSON.stringify(ctx.params.entities);
        }
    }
});

// Load API Gateway
broker.createService({
    name: "api",
    mixins: [ApiService],
    settings: {
        routes: [
            {
                path: "/api1",
                whitelist: ["test1.hello"],
                bodyParsers: {
                    json: true
                }				
            },
            {
                path: "/api2",
                whitelist: ["test2.hello"],
                bodyParsers: {
                    json: true
                }
            }
        ]
    }
});

// Start server
broker.start();
```

It works fine in your first route because API gateway [has **one** default route where body-parsers is enabled](https://github.com/moleculerjs/moleculer-web/blob/15d3175596b4ea53f416d2df5e8f166412551b33/src/index.js#L61) and the mixins logic merge the settings, so your first route will be merged with the default route.

**Comment by jjgumucio** [comment] 2019-04-23 22:47
I think this should be documented!

I have been banging my head for 3 days now trying to fix this same problem on my service.

Thanks for the solution @icebob 

BTW: Thanks for this fantastic piece of software and tool! 🥂

**Comment by AndreMaz** [comment] 2019-04-24 10:24
Sorry for your inconvenience. I've updated the docs.

Glad you like Moleculer :smile:

**Comment by icebob** [comment] 2019-04-24 16:19
Thanks @jjgumucio & @AndreMaz

**Closed by icebob** 2019-04-24 16:19 UTC
